### ISSUE TITLE
selecto.main clientlib could not be built.

### ISSUE THREAD

**Issue by CptBartender** [ahmed-musallam/aem-selecto#1]
On a raw AEM 6.3.1 instance, the clientlib selecto.main is not built successfully, which renders the tool unusable. Below is a stack trace visible when refreshing the /etc/selecto.html page:

> 11.01.2018 11:12:04.217 *INFO* [172.17.0.1 [1515669124205] GET /apps/selecto/components/content/main/clientlibs/main.min.js HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.LibraryCacheImpl Invalidating library /apps/selecto/components/content/main/clientlibs/main
11.01.2018 11:12:04.220 *INFO* [172.17.0.1 [1515669124205] GET /apps/selecto/components/content/main/clientlibs/main.min.js HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl detected [JS, CSS] library: /apps/selecto/components/content/main/clientlibs/main, sourced from 12 files.
11.01.2018 11:12:04.220 *ERROR* [172.17.0.1 [1515669124205] GET /apps/selecto/components/content/main/clientlibs/main.min.js HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl Error while saving changes: javax.jcr.RepositoryException: Error during assembly of /apps/selecto/components/content/main/clientlibs/main.js. reverting.
11.01.2018 11:12:04.220 *ERROR* [172.17.0.1 [1515669124205] GET /apps/selecto/components/content/main/clientlibs/main.min.js HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl Error while sending cached library: javax.jcr.RepositoryException: Error during assembly of /apps/selecto/components/content/main/clientlibs/main.js
11.01.2018 11:12:04.220 *ERROR* [172.17.0.1 [1515669124205] GET /apps/selecto/components/content/main/clientlibs/main.min.js HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryServlet Cannot create library for /apps/selecto/components/content/main/clientlibs/main.min.js
java.io.IOException: Error while sending cached library: javax.jcr.RepositoryException: Error during assembly of /apps/selecto/components/content/main/clientlibs/main.js
        at com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl.send(HtmlLibraryManagerImpl.java:1308)
        at com.adobe.granite.ui.clientlibs.impl.HtmlLibraryWriter.send(HtmlLibraryWriter.java:549)
        at com.adobe.granite.ui.clientlibs.impl.HtmlLibraryImpl.send(HtmlLibraryImpl.java:170)
        at com.adobe.granite.ui.clientlibs.impl.HtmlLibraryServlet.doGet(HtmlLibraryServlet.java:92)

Using trial-and-error, I managed to narrow the issues to two files:

1. In file HttpService.js, renaming or commenting out declaration of HttpService.prototype.delete seems to allow the clientlib to build
2. Similarly, commenting out the entire main.js file out from the clientlib (in clientlib's js.txt) allows  the clientlib to be built (I did not investigate which lines cause the issues in main.js).

Please let me know if you need further info from my side or help with tracking the issue down

**Comment by ahmed-musallam** [comment]
Hi @CptBartender thanks for opening this issue.

I went ahead and did the following to try and replicate this issue:

1. Started a fresh AEM 6.3 instance (100% clean)
2. Deployed the [AEM-6.3-SERVICE-PACK-1](https://www.adobeaemcloud.com/content/marketplace/marketplaceProxy.html?packagePath=/content/companies/public/adobe/packages/cq630/servicepack/AEM-6.3-Service-Pack-1)
3. Downloaded and deployed selecto package `aem-selecto.ui.apps-1.0.0.zip` from the [release page] (https://github.com/ahmed-musallam/aem-selecto/releases)
3. navigate to selecto at http://localhost:4502/etc/selecto.html
4. checked error log through this whole process

Selecto seems to be working as expected and don't see the error you are referring to. Could you please replicate my steps and let me know if you still see the error?

Do you have any other extra CFP or other packages installed?

**Comment by CptBartender** [comment]
Hey @ahmed-musallam, I followed the steps you described and reached the same result. Then I started digging around and disabled (what is enabled by default in our setup) minification and compression of clientlibs in com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl OSGi configuration, and the page seems to be loading correctly now.

Could you please enable minification and compression between steps #2 and #3 and verify if the app still works as expected on your end?

**Comment by CptBartender** [comment]
Hey @ahmed-musallam,

please take a look at [the PR](https://github.com/ahmed-musallam/aem-selecto/pull/2) I've just raised - it appears to be fixing the problem on my end.

Cheers

**Comment by ahmed-musallam** [comment]
@CptBartender good catch, merged your PR and released v1.0.1.

Thanks!
